=== modelica/fmi-ls-ref/schema/fmi3LayeredStandardReferenceExperiments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
    <xs:annotation>
        <xs:documentation>
Copyright(c) 2023-2025 Modelica Association Project "FMI".
             All rights reserved.

This file is licensed by the copyright holders under the 2-Clause BSD License
(https://opensource.org/licenses/BSD-2-Clause):

----------------------------------------------------------------------------
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

- Redistributions of source code must retain the above copyright notice,
 this list of conditions and the following disclaimer.

- Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----------------------------------------------------------------------------
        </xs:documentation>
    </xs:annotation>

    <xs:simpleType name="TStimuliMatchBy">
        <xs:restriction base="xs:string">
            <xs:enumeration value="systemConnectorName"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="Experiments">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Experiment" minOccurs="1" maxOccurs="unbounded" type="TExperiment"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="description" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="TExperiment">
        <xs:sequence>
            <xs:element name="Parameters" minOccurs="0" maxOccurs="unbounded" type="TParameters"/>
            <xs:element name="Stimuli" minOccurs="0" maxOccurs="unbounded" type="TStimuli"/>
            <xs:element name="References" minOccurs="0" maxOccurs="unbounded" type="TReferences"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="target" type="xs:anyURI"/>
        <xs:attribute name="startTime" type="xs:double"/>
        <xs:attribute name="stopTime" type="xs:double"/>
        <xs:attribute name="tolerance" type="xs:double"/>
        <xs:attribute name="stepSize" type="xs:double"/>
    </xs:complexType>

    <xs:complexType name="TParameters">
        <xs:attribute name="type" type="xs:string" use="optional" default="application/x-ssp-parameter-set">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    This attribute specifies the MIME type of the parameter data source, which
                    defaults to application/x-ssp-parameter-set to indicate the SSV file format
                    as specified in the SSP standard.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="source" type="xs:anyURI" use="required">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    URI of the parameter data source. For SSP archives, this is resolved
                    relative to the layered standard reference file.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="mapping" type="xs:anyURI">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    Optional SSP parameter-mapping file (SSM) used to map source names to
                    experiment target parameter names.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="TStimuli">
        <xs:attribute name="type" type="xs:string" use="optional" default="text/csv">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    This attribute specifies the MIME type of the stimuli data source, which
                    defaults to text/csv.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="source" type="xs:anyURI" use="required">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    URI of the stimuli data source. For SSP archives, this is resolved relative
                    to the layered standard reference file.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="matchBy" type="TStimuliMatchBy" default="systemConnectorName">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    Default binding mode for stimuli columns. The current layered-standard
                    implementation only supports systemConnectorName.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="mapping" type="xs:anyURI">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    Optional SSP parameter-mapping file (SSM) used to map stimuli names to
                    system connector names.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="TReferences">
        <xs:sequence>
            <xs:element name="Signal" minOccurs="0" maxOccurs="unbounded" type="TSignal"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" use="optional" default="text/csv">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    This attribute specifies the MIME type of the reference data source, which
                    defaults to text/csv.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="source" type="xs:anyURI" use="required">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    URI of the reference result data source. For SSP archives, this is resolved
                    relative to the layered standard reference file.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="mapping" type="xs:anyURI">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    Optional SSP parameter-mapping file (SSM) used to map reference signal names
                    to SSP output connector names.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="matchBy" type="TStimuliMatchBy" default="systemConnectorName">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    Default binding mode for reference signal columns. The current layered-standard
                    implementation only supports systemConnectorName.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="TSignal">
        <xs:attribute name="name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    Name of the reference signal to include in comparison.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== modelica/fmi-ls-ref/docs/examples/fmi_ls_ref_experiments_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<Experiments
    name="Smoke Tests"
    description="Simple set of smoke tests to validate the integration of the SSP into a simulation engine."
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../schema/fmi3LayeredStandardReferenceExperiments.xsd">
    <Experiment name="Test1" description="Baseline steady-state test" target="SystemStructure.ssd"
        startTime="0.0" stopTime="10.0" stepSize="0.001" tolerance="0.004">
        <Parameters source="test1-params.ssv" mapping="test1-params.ssm"/>
        <Stimuli source="test1-in.csv" matchBy="systemConnectorName" mapping="test1-in.ssm"/>
        <References source="test1-ref.csv" matchBy="systemConnectorName" mapping="test1-ref.ssm">
            <Signal name="y"/>
            <Signal name="z"/>
        </References>
    </Experiment>
    <Experiment name="Test2" description="Baseline dynamic test" target="SystemStructure.ssd" startTime="0.0" stopTime="15.0" stepSize="0.010">
        <Parameters source="dynamic-params.ssv" mapping="dynamic-params.ssm"/>
        <Stimuli source="test2-in.csv" type="text/csv" matchBy="systemConnectorName" mapping="test2-in.ssm"/>
        <References source="test2-ref.hdf5" type="application/hdf5" matchBy="systemConnectorName" mapping="test2-ref.ssm">
            <Signal name="u"/>
            <Signal name="v"/>
        </References>
    </Experiment>
</Experiments>
